#!/usr/bin/env bash
# call bolt_watchdog.sh passing app's folder
test -s $HOME/.rvm/scripts/rvm && source $HOME/.rvm/scripts/rvm &> /dev/null
. $HOME/.bash_profile
cd `dirname $0`
$(bundle show bolt)/lib/bolt_watchdog.sh "$(pwd)"
